[package]
name = "etherealpost"
version = "0.1.0"
authors = ["Seputaes <seputaes@sep.gg>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
