on:
  push:
  pull_request:
  schedule:
    - cron: '0 2 * * *'

jobs:
  test_and_check:
    name: Build and Test
    strategy:
      fail-fast: false
      matrix:
        rust: ["stable", "beta", "nightly"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources from git
        uses: actions/checkout@v2
      - name: Setup Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Cargo Test
        uses: actions-rs/cargo@v1
        with:
          command: test

  linting:
    name: rustfmt and Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sorces from git
        uses: actions/checkout@v2
      - name: Setup Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt
          override: true
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all -- -D clippy::all
      - name: Check rustfmt
        if: always()
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check